# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "opendal-cloud"
publish = false

authors = ["Apache OpenDAL <dev@opendal.apache.org>"]
edition = "2021"
homepage = "https://opendal.apache.org/"
license = "Apache-2.0"
repository = "https://github.com/apache/opendal"
rust-version = "1.82"
version = "0.46.0"

[features]
# Cloud services (based on tested services from backup)
default = [
  "services-aliyun-drive",
  "services-b2",
  "services-dashmap",
  "services-dropbox",
  "services-gdrive",
  "services-huggingface",
  "services-ipfs",
  "services-koofr",
  "services-moka",
  "services-onedrive",
  "services-seafile",
  "services-swift",
  "services-upyun",
  "services-vercel-artifacts",
  "services-yandex-disk",
  "services-alluxio",
]

# Cloud Storage Services (verified to exist)
services-aliyun-drive = ["opendal/services-aliyun-drive"]
services-alluxio = ["opendal/services-alluxio"]
services-b2 = ["opendal/services-b2"]
services-dashmap = ["opendal/services-dashmap"]
services-dropbox = ["opendal/services-dropbox"]
services-gdrive = ["opendal/services-gdrive"]
services-huggingface = ["opendal/services-huggingface"]
services-ipfs = ["opendal/services-ipfs"]
services-koofr = ["opendal/services-koofr"]
services-moka = ["opendal/services-moka"]
services-onedrive = ["opendal/services-onedrive"]
services-seafile = ["opendal/services-seafile"]
services-swift = ["opendal/services-swift"]
services-upyun = ["opendal/services-upyun"]
services-vercel-artifacts = ["opendal/services-vercel-artifacts"]
services-yandex-disk = ["opendal/services-yandex-disk"]

# ABI3 support
abi3 = ["pyo3/abi3-py311"]

[lib]
name = "opendal_cloud"
crate-type = ["cdylib"]
doc = false
path = "src/lib.rs"

[dependencies]
bytes = { workspace = true }
chrono = { workspace = true }
dict_derive = { workspace = true }
futures = { workspace = true }
opendal = { workspace = true }
opendal-python-shared = { path = "../../shared" }
pyo3 = { workspace = true }
pyo3-async-runtimes = { workspace = true }
tokio = { workspace = true }
